version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get -y install wget zip python3-pip && sudo pip3 install setuptools-scm && sudo pip3 install b2sdk
      - run: wget -O master.zip https://github.com/rehmatworks/fastcp/archive/refs/heads/master.zip && unzip -qq master.zip && rm master.zip && rm -rf fastcp && mv fastcp-master fastcp && zip -qq -r latest.zip fastcp
      - run: python3 ./update.py